version: '3'
services:

  experiments:
    build: .
    ports:
      - 127.0.0.1:6007:6007
    command: supervisord -n -c /etc/supervisor/supervisord.conf
    volumes:
      - ./experiments:/experiments
    working_dir: /experiments/

#    deploy:
#      resources:
#        reservations:
#          devices:
#          - driver: nvidia
#            device_ids: ['0']
#            capabilities: [gpu]
